openapi: 3.0.0
info:
  title: Portfolio
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: simple
  - name: to_do_app
paths:
  /simple/add-two-number:
    post:
      tags:
        - simple
      description: Add 2 number
      summary: Add 2 number
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputAdd2Number'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebResponse_add_2_number'
        '400':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBadRequest'
  /to-do:
    post:
      tags:
        - to_do_app
      description: Add to do list
      summary: Add to do list 
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputAddTodo'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseAddTodo'
        '400':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorBadRequest'


components:
  # securitySchemes:
  #   CategoryAuth:
  #     type: apiKey
  #     in: header
  #     name: X-API-Key
  #     description: Authentication for Category API
  schemas:
    InputAdd2Number:
      type: object
      properties:
        number_1:
          type: number
        number_2:
          type: number
    
    InputAddTodo:
      type: object
      properties:
        title:
          type: string
      additionalProperties: false
      required:
        - title

    WebResponse_add_2_number:
      type: object
      properties:
        status:
          type: string
        data:
          type: number
      additionalProperties: false
      required:
        - status
        - data

    ErrorBadRequest:
      type: object
      properties:
        status:
          type: string
        data:
          type: string # null
        message:
          type: string
      additionalProperties: false
      required:
        - status
        - data
        - message

    ResponseAddTodo:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            rows_affected:
              type: integer
          required:
            - rows_affected
          additionalProperties: false
      additionalProperties: false
      required:
        - status
        - data